export enum MemberSections {
    ADMINISTRATION = 'ADMINISTRATION',
    ACADEMIC_COUNCIL = 'ACADEMIC_COUNCIL',
    COUNCIL_OF_YOUNG_SCIENTISTS = 'COUNCIL_OF_YOUNG_SCIENTISTS',
    DEPARTMENT_OF_VIROLOGY = 'DEPARTMENT_OF_VIROLOGY',
    DEPARTMENT_OF_MOLECULAR_GENETIC_RESEARCH = 'DEPARTMENT_OF_MOLECULAR_GENETIC_RESEARCH',
    DEPARTMENT_OF_PROTOZOOLOGY = 'DEPARTMENT_OF_PROTOZOOLOGY',
    DEPARTMENT_OF_PHARMACOLOGY_AND_TOXICOLOGY = 'DEPARTMENT_OF_PHARMACOLOGY_AND_TOXICOLOGY',
    PRODUCTION_DEPARTMENT = 'PRODUCTION_DEPARTMENT',
}

export interface Member {
    id: number;
    fullName: string;
    jobName?: string;
    status?: string;
    section: MemberSections;
    email?: string;
    phone?: string;
    avatar?: string;
    position: number;
}
